name: Compile and Upload Typst CVs
on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
      - name: Checkout cv.typ template repository
        uses: actions/checkout@v4
        with:
          repository: jskherman/cv.typ
          path: template
      - name: Compile Typst files
        uses: jskherman/typst-action@main
        with:
          source_file: |
            resume.typ
          options: |
            --font-path
            ./fonts
            --root
            .
            gh-pages/resume.pdf

      - name: Install pdf2svg
        run: sudo apt install pdf2svg

      - name: Convert PDF to SVG
        run: pdf2svg gh-pages/resume.pdf gh-pages/resume%d.svg all

      - name: Upload Page Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: gh-pages
  
  download_and_deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4

      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4