name: Compile and Upload Typst CVs
on: [workflow_dispatch, push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
      - name: Checkout cv.typ template repository
        uses: actions/checkout@v4
        with:
          repository: jskherman/cv.typ
          path: template
          ref: v0.4.0
      - name: Compile Typst files
        uses: waseemr02/typst-action@main
        with:
          source_file: |
            resume.typ
          options: |
            --font-path
            ./fonts
            --root
            .

      - name: Upload resume as artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: docs/resume.pdf
  
      - name: Move resume to gh-pages
        run: mv docs/resume.pdf gh-pages/

      - name: Install pdf2svg
        run: sudo apt install pdf2svg

      - name: Convert PDF to SVG
        run: pdf2svg gh-pages/resume.pdf gh-pages/resume%d.svg all
        
      - name: Setup Pages
        if: github.ref == 'refs/heads/typst'
        uses: actions/configure-pages@v4

      - name: Upload Page Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./gh-pages
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Setup Pages
        if: github.ref == 'refs/heads/typst'
        uses: actions/configure-pages@v4

      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
